Repository ClassicPress/ClassicPress, pull requests merged in 2021-07, with the labels that each got.

#697 Semantic elements for non-link links: class-wp-posts-list-table.php
  src/wp-admin/includes/class-wp-comments-list-table.php
  src/wp-admin/includes/class-wp-posts-list-table.php
  src/wp-admin/includes/class-wp-terms-list-table.php
  src/wp-admin/js/edit-comments.js
  src/wp-admin/js/inline-edit-post.js
  src/wp-admin/js/inline-edit-tax.js
Labels: accessibility, community reviewed

#691 Merge/wp r44353: Administration: Update default fallback color for SVG icons.
  src/wp-admin/includes/misc.php
  src/wp-includes/general-template.php
Labels: accessibility, community reviewed

#689 WP-r44750: Accessibility: Fix a regression in the old media modal pagtion links.
  src/wp-admin/css/deprecated-media.css
Labels: accessibility, community reviewed

#698 WP-r42784: Accessibility: Change the media upload "Dismiss error" lin…
  src/wp-admin/async-upload.php
  src/wp-admin/css/media.css
Labels: accessibility, community reviewed

#696 WP-r42440: Accessibility: use `aria-current` for the paginated post l…
  src/wp-includes/post-template.php
  tests/phpunit/tests/post/template.php
Labels: accessibility, community reviewed

#685 WP-r43829: Accessibility: Media: Improve the usage of a few label elements in the media templates.
  src/wp-includes/media-template.php
Labels: accessibility, community reviewed

#562 Accessibility Improvement: Alt text description
  src/wp-admin/css/media.css
  src/wp-admin/includes/media.php
  src/wp-includes/css/media-views.css
  src/wp-includes/js/media-views.js
  src/wp-includes/js/media/views/attachment/details.js
  src/wp-includes/media-template.php
  tests/qunit/index.html
Labels: accessibility, community reviewed

#693 WP-r43633: Media: Improve display and accessibility of meta data in d…
  src/wp-includes/functions.php
  src/wp-includes/media-template.php
  src/wp-includes/media.php
  tests/phpunit/tests/functions.php
Labels: accessibility, community reviewed, discussion

#753 Fix for Ajax Autosave Unit Tests
  tests/phpunit/tests/ajax/Autosave.php
Labels: build/tests
