Repository ClassicPress/ClassicPress, pull requests merged in 2021-05, with the labels that each got.

#710 Add some clarity to contributors file
  .github/CONTRIBUTING.md
Labels: documentation

#645 Add new filter to allow wp_mail() to be bypassed
  src/wp-includes/pluggable.php
  tests/phpunit/tests/mail.php
Labels: community reviewed, enhancement

#593 Ensure user data is fully deleted on Multisite installs
  src/wp-admin/includes/ms.php
  src/wp-admin/includes/user.php
  src/wp-includes/ms-default-filters.php
  src/wp-includes/ms-functions.php
  tests/phpunit/tests/multisite/wpmuValidateUserSignup.php
Labels: WP backport, bug, community reviewed

#694 WP-r44416: Accessibility: Themes: use `aria-current` for the `Walker_…
  src/wp-includes/class-walker-page.php
Labels: accessibility

#657 WP-r50256: Media: Pause any playing media when closing the the media …
  src/wp-includes/js/media-views.js
  src/wp-includes/js/media/views/modal.js
Labels: WP backport, bug, community reviewed

#639 Update the Root Certificate bundle
  src/wp-includes/certificates/ca-bundle.crt
Labels: WP backport, community reviewed

#729 Welcome new Contributors
  .github/workflows/welcome-new-contributors.yml
Labels: discussion, enhancement
