Repository ClassicPress/ClassicPress, pull requests merged in 2022-09, with the labels that each got.

#1097 WP-r51582: Set the MySQLi error reporting off for PHP 8.1
  src/wp-includes/wp-db.php
Labels: type: wp backport, status: community reviewed, scope: php8, task: needs 2nd review

#1022 Accessibility: Themes: use aria-current for the Walker_Nav_Menu current link (and patch)
  src/wp-includes/class-walker-nav-menu.php
Labels: type: wp backport, task: needs 2nd review

#884 Improve sanitize_key() to cover all non-scaler value input
  src/wp-includes/formatting.php
  tests/phpunit/tests/formatting/sanitizeKey.php
Labels: task: needs 2nd review

#979 Fix fatal error uploading media on PHP8
  src/wp-admin/includes/image.php
  tests/phpunit/data/images/sugarloaf-mountain.jpg
  tests/phpunit/tests/image/functions.php
  tests/phpunit/tests/image/meta.php
Labels: type: wp backport, status: community reviewed, scope: php8

#811 Fix wp core check update in wp cli
  src/wp-includes/class-fix-wpcli.php
  src/wp-settings.php
Labels: type: feature request, task: documentation, status: community reviewed

#843 WP-r52083: Add new wp_mail() success hook
  src/wp-includes/pluggable.php
Labels: type: feature request, type: wp backport, task: needs 2nd review

#867 Remove feed reference to non-existent file
  src/wp-includes/feed-atom.php
  tests/phpunit/tests/feed/atom.php
Labels: type: wp backport

#851 WP-r51586: Rename the readonly() function to `wp_readonly()`
  phpunit.xml.dist
  src/wp-includes/general-template.php
  src/wp-includes/php-compat/readonly.php
  tests/phpunit/multisite.xml
  tests/phpunit/tests/general/template_CheckedSelectedHelper.php
Labels: type: wp backport, status: community reviewed, scope: php8

#950 WP-r52837: Media: Store attachment’s file size in metadata
  src/wp-admin/includes/image.php
  src/wp-admin/includes/media.php
  src/wp-includes/class-wp-image-editor-gd.php
  src/wp-includes/class-wp-image-editor-imagick.php
  src/wp-includes/functions.php
  src/wp-includes/media.php
  src/wp-includes/post.php
  tests/phpunit/tests/file.php
  tests/phpunit/tests/functions.php
  tests/phpunit/tests/image/editorGd.php
  tests/phpunit/tests/image/editorImagick.php
  tests/phpunit/tests/image/functions.php
Labels: type: wp backport, status: community reviewed, task: needs 2nd review

#1111 Upgrade/Install: Remove _copy_dir() function
  src/wp-admin/includes/update-core.php
Labels: type: wp backport

#1109 Set default show_avatars option to off
  src/wp-admin/includes/schema.php
  tests/phpunit/tests/avatar.php
  tests/phpunit/tests/rest-api/rest-comments-controller.php
  tests/phpunit/tests/rest-api/rest-users-controller.php
  tests/phpunit/tests/schema.php
  tests/qunit/fixtures/wp-api-generated.js
Labels: type: feature request

#863 Update ID3 library
  src/wp-admin/includes/media.php
  src/wp-includes/ID3/getid3.lib.php
  src/wp-includes/ID3/getid3.php
  src/wp-includes/ID3/module.audio-video.asf.php
  src/wp-includes/ID3/module.audio-video.flv.php
  src/wp-includes/ID3/module.audio-video.matroska.php
  src/wp-includes/ID3/module.audio-video.quicktime.php
  src/wp-includes/ID3/module.audio-video.riff.php
  src/wp-includes/ID3/module.audio.ac3.php
  src/wp-includes/ID3/module.audio.dts.php
  src/wp-includes/ID3/module.audio.flac.php
  src/wp-includes/ID3/module.audio.mp3.php
  src/wp-includes/ID3/module.audio.ogg.php
  src/wp-includes/ID3/module.tag.apetag.php
  src/wp-includes/ID3/module.tag.id3v1.php
  src/wp-includes/ID3/module.tag.id3v2.php
  src/wp-includes/ID3/module.tag.lyrics3.php
  src/wp-includes/ID3/readme.txt
Labels: type: wp backport, scope: php8

#1110 Change default_comment_status to closed
  src/wp-admin/includes/schema.php
  tests/phpunit/tests/comment-submission.php
  tests/phpunit/tests/comment.php
  tests/phpunit/tests/comment/commentForm.php
  tests/phpunit/tests/feed/rss2.php
  tests/phpunit/tests/post.php
  tests/phpunit/tests/rest-api.php
  tests/phpunit/tests/rest-api/rest-comments-controller.php
  tests/phpunit/tests/rest-api/rest-schema-setup.php
  tests/phpunit/tests/schema.php
  tests/phpunit/tests/xmlrpc/wp/newComment.php
Labels: type: feature request

#1101 Coding Standards from Ticket 45934
  phpcs.xml.dist
  src/wp-admin/includes/export.php
  src/wp-admin/includes/image.php
  src/wp-admin/includes/import.php
  src/wp-admin/includes/plugin.php
  src/wp-admin/includes/upgrade.php
  src/wp-admin/post.php
  src/wp-admin/update-core.php
  src/wp-admin/user-edit.php
  src/wp-includes/category-template.php
  src/wp-includes/class-wp-comment-query.php
  src/wp-includes/class-wp-locale.php
  src/wp-includes/class-wp-text-diff-renderer-table.php
  src/wp-includes/class-wp-theme.php
  src/wp-includes/class-wp-xmlrpc-server.php
  src/wp-includes/formatting.php
  src/wp-includes/functions.php
  src/wp-includes/general-template.php
  src/wp-includes/load.php
  src/wp-includes/media.php
  src/wp-includes/post.php
  src/wp-includes/template.php
  src/wp-includes/wp-db.php
  tests/phpunit/tests/avatar.php
  tests/phpunit/tests/functions.php
  tests/phpunit/tests/http/base.php
  tests/phpunit/tests/http/curl.php
  tests/phpunit/tests/post/output.php
  tests/phpunit/tests/shortcode.php
  tests/phpunit/tests/user.php
  tests/phpunit/wp-mail-real-test.php
Labels: type: wp backport, status: needs review

#1021 WP-r48601: Ensure that a server hostname can be set by using network_home_url()
  src/wp-includes/ms-functions.php
  src/wp-includes/pluggable.php
Labels: type: wp backport, task: needs 2nd review

#902 WP-r52585: Check if the disk_free_space() exists
  src/wp-admin/includes/file.php
  src/wp-admin/includes/update-core.php
Labels: type: wp backport, scope: php8, task: needs 2nd review

#806 WP-r47856: Posts, Post Types: Pass the post object to the delete_attachment action.
  src/wp-includes/post.php
Labels: type: wp backport

#852 WP-r52141: Update `_edit_last` meta when posts are bulk edited
  src/wp-admin/includes/post.php
Labels: type: wp backport

#926 External Libraries: Update random_compat to v2.0.21
  src/wp-includes/random_compat/byte_safe_strings.php
  src/wp-includes/random_compat/cast_to_int.php
  src/wp-includes/random_compat/error_polyfill.php
  src/wp-includes/random_compat/random.php
  src/wp-includes/random_compat/random_bytes_com_dotnet.php
  src/wp-includes/random_compat/random_bytes_dev_urandom.php
  src/wp-includes/random_compat/random_bytes_libsodium.php
  src/wp-includes/random_compat/random_bytes_libsodium_legacy.php
  src/wp-includes/random_compat/random_bytes_mcrypt.php
  src/wp-includes/random_compat/random_bytes_openssl.php
  src/wp-includes/random_compat/random_int.php
Labels: type: wp backport, scope: php8

#856 WP-r52188: Add support for new tags in force_balance_tags()
  src/wp-includes/formatting.php
  tests/phpunit/tests/formatting/balanceTags.php
Labels: type: wp backport, task: needs 2nd review
