Repository ClassicPress/ClassicPress, pull requests merged in 2022-11, with the labels that each got.

#1136 Update GitHub actions to avoid node deprecation warnings
  .github/workflows/coding-standards.yml
  .github/workflows/javascript-tests.yml
  .github/workflows/php-compatibility.yml
  .github/workflows/phpunit-tests.yml
Labels: scope: build/tests, status: needs review

#1105 Try running PHPUnit tests on Ubuntu-latest
  .github/workflows/phpunit-tests.yml
Labels: scope: build/tests, status: needs review

#1153 Fix `Tests_Login::test_reset_password` for PHP 8
  .github/workflows/phpunit-tests.yml
  tests/phpunit/tests/login.php
Labels: scope: php8, task: needs 2nd review

#1156 Coding Standards from Ticket 50913
  src/wp-includes/pomo/po.php
  tests/phpunit/includes/phpunit7/testcase.php
Labels: type: wp backport, scope: php8

#881 Remove JavaScript and CSS type attributes for HTML5 validity
  src/wp-content/themes/twentyseventeen/functions.php
  src/wp-content/themes/twentysixteen/functions.php
  src/wp-includes/admin-bar.php
  src/wp-includes/class.wp-scripts.php
  src/wp-includes/class.wp-styles.php
  src/wp-includes/embed.php
  src/wp-includes/formatting.php
  src/wp-includes/media.php
  src/wp-includes/script-loader.php
  src/wp-includes/theme.php
  src/wp-includes/widgets/class-wp-widget-archives.php
  src/wp-includes/widgets/class-wp-widget-categories.php
  src/wp-includes/widgets/class-wp-widget-recent-comments.php
  tests/phpunit/tests/dependencies/scripts.php
  tests/phpunit/tests/dependencies/styles.php
  tests/phpunit/tests/functions.php
Labels: type: wp backport, status: needs review

#896 Add/lazy loading
  src/wp-includes/default-filters.php
  src/wp-includes/deprecated.php
  src/wp-includes/media.php
  src/wp-includes/pluggable.php
  src/wp-includes/post-thumbnail-template.php
  tests/phpunit/tests/avatar.php
  tests/phpunit/tests/media.php
Labels: type: wp backport, status: needs review

#1163 WP-r46270:: Make sure `$type_attr` is always defined in `_custom_background_cb()`.
  src/wp-includes/theme.php
Labels: type: wp backport

#1096 WP-r46148: Avoid a PHP warning in wp_xmlrpc_server::minimum_args() if $args is not an array.
  src/wp-includes/class-wp-xmlrpc-server.php
Labels: type: wp backport, scope: php8, status: needs review

#1165 Fix for PHP8 error in "ClassicPress News" widget
  src/wp-includes/class-wp-feed-cache.php
  src/wp-includes/feed.php
Labels: type: wp backport, scope: php8

#1159 PHP Dashboard Warnings and update about.php
  src/wp-admin/about.php
  src/wp-admin/css/edit.css
  src/wp-admin/includes/dashboard.php
  src/wp-admin/includes/nav-menu.php
Labels: type: bug, type: wp backport, scope: php8

#1123 Posts: Avoid the use of globals in get_the_content() and related functions #1082
  src/wp-includes/cache-compat.php
  src/wp-includes/class-wp-query.php
  src/wp-includes/formatting.php
  src/wp-includes/media.php
  src/wp-includes/post-template.php
  src/wp-includes/query.php
  tests/phpunit/tests/post/getTheContent.php
  tests/phpunit/tests/post/getTheExcerpt.php
  tests/phpunit/tests/query/generatePostdata.php
Labels: type: wp backport

#945 WP-r52921: Taxonomy: Use get_terms instead of a database lookup in term_exists()
  src/wp-includes/taxonomy.php
  tests/phpunit/tests/term/getTerm.php
  tests/phpunit/tests/term/splitSharedTerm.php
  tests/phpunit/tests/term/termExists.php
  tests/phpunit/tests/term/wpGetObjectTerms.php
Labels: type: wp backport, task: needs 2nd review

#1173 Update importer API
  src/wp-admin/import.php
  src/wp-admin/includes/import.php
Labels: type: feature request, status: community reviewed
