Repository ClassicPress/ClassicPress, pull requests merged in 2022-08, with the labels that each got.

#946 WP-r45310: Remove duplicate `font-face` declaration
  src/wp-includes/css/dashicons.css
Labels: type: wp backport, status: community reviewed

#1094 WP-r53917: External Libraries: Upgrade PHPMailer to version 6.6.4.
  src/wp-includes/PHPMailer/PHPMailer.php
  src/wp-includes/PHPMailer/SMTP.php
Labels: type: wp backport, task: needs 2nd review

#1066 FUNDING.yml
  .github/FUNDING.yml
Labels: scope: community, task: needs 2nd review

#1020 Pass EXIF Data to the wp_read_image_metadata filter #904
  src/wp-admin/includes/image.php
Labels: type: wp backport, task: needs 2nd review

#942 WP-r52825: General: Improve MS Edge user-agent sniff.
  src/wp-includes/vars.php
Labels: type: wp backport
