Repository ClassicPress/ClassicPress, pull requests merged in 2022-12, with the labels that each got.

#1181 wp_image_src_get_dimensions() may throw warning or return wrong values
  src/wp-includes/media.php
  tests/phpunit/tests/media.php
Labels: type: bug, type: wp backport

#1185 add missing end tags for the Go to site link and paragraph
  src/wp-login.php
Labels: type: bug, status: community reviewed

#1178 Updated bug reporting link
  src/wp-admin/includes/class-wp-automatic-updater.php
Labels: type: bug, scope: community, task: documentation, status: community reviewed

#1134 wp-r54420:: Remove instances of _wp_http_referer from GET forms in the admin.
  src/wp-includes/functions.php
  tests/phpunit/tests/functions/wpNonceField.php
  tests/phpunit/tests/functions/wpRefererField.php
Labels: type: wp backport, status: community reviewed

#1174 Make external tests less flaky
  tests/phpunit/tests/external-http/basic.php
  tests/phpunit/tests/http/base.php
Labels: scope: build/tests, status: community reviewed

#1196 WP-r42632: Themes: Use api v. 1.2 to query theme information.
  src/wp-admin/includes/ajax-actions.php
  src/wp-admin/includes/class-theme-upgrader.php
  src/wp-admin/includes/theme.php
  src/wp-admin/js/theme.js
  src/wp-admin/theme-install.php
  src/wp-includes/class-wp-customize-manager.php
Labels: type: wp backport, task: needs 2nd review
