Repository ClassicPress/ClassicPress, pull requests merged in 2022-10, with the labels that each got.

#1031 Default filters WP Plugins by "classicpress" keyword
  src/wp-admin/menu.php
  src/wp-admin/network/menu.php
  src/wp-admin/plugins.php
Labels: type: feature request, status: community reviewed

#805 WP-r47582: Pass the post object to the before_delete_post, delete_post, deleted_post, and after_delete_post actions.
  src/wp-includes/post.php
Labels: type: wp backport

#1135 Custom issue templates and template chooser
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/wp_backport.yml
Labels: type: feature request, scope: community, status: community reviewed

#1124 WP-r50921: Add support for `Update URI` plugin header
  src/wp-admin/includes/class-wp-plugin-install-list-table.php
  src/wp-admin/includes/plugin.php
  src/wp-admin/includes/update.php
  src/wp-includes/update.php
Labels: type: wp backport, task: needs 2nd review

#1133 WP-r54427: External Libraries: Upgrade PHPMailer to version 6.6.5
  src/wp-includes/PHPMailer/PHPMailer.php
  src/wp-includes/PHPMailer/SMTP.php
Labels: type: wp backport

#1129 wp-r47251:: Store the original attachment URL in the `_source_url` post meta value
  src/wp-admin/includes/media.php
Labels: type: wp backport, task: needs 2nd review

#943 WP-r52841: Quick/Bulk Edit taxonomy improvement
  src/wp-admin/includes/template.php
Labels: type: wp backport, task: needs 2nd review
