Repository ClassicPress/ClassicPress, pull requests merged in 2023-01, with the labels that each got.

#1209 Fix incomplete `preg_match` regex in `get_the_post_thumbnail()`
  src/wp-includes/post-thumbnail-template.php
Labels: type: bug, status: community reviewed

#1207 Avoid call to non-existent `is_taxonomy_viewable()` function
  src/wp-includes/admin-bar.php
Labels: type: bug, task: needs 2nd review

#1214 docs: Updated readme.html
  src/readme.html
Labels: status: has pr, status: needs review
