Repository ClassicPress/ClassicPress, pull requests merged in 2023-06, with the labels that each got.

#1167 WP-r53886: Formatting: Add support for Enums in `is_serialized()`.
  src/wp-includes/functions.php
  tests/phpunit/tests/functions/isSerialized.php
Labels: type: wp backport, status: community reviewed, scope: php8

#846 WP-r52092: Quick/Bulk Edit: Disable auto-correct for slugs.
  src/wp-admin/includes/class-wp-posts-list-table.php
Labels: type: feature request

#1089 WP-r53900: Prevent the last character of names in “From” headers from being trimmed.
  src/wp-includes/pluggable.php
  tests/phpunit/tests/mail.php
Labels: type: bug, type: wp backport, task: needs 2nd review

#1073 WP-r53733: Correct the check for non-existing post in get_post_permalink()
  src/wp-includes/link-template.php
  tests/phpunit/tests/link/getPostPermalink.php
Labels: type: bug, type: wp backport, status: needs review

#1240 fix: Removed petitions widget
  src/wp-admin/includes/ajax-actions.php
  src/wp-admin/includes/dashboard.php
  tests/phpunit/data/admin/features.json
  tests/phpunit/tests/admin/includesDashboard.php
Labels: status: has pr
