Repository ClassicPress/ClassicPress, pull requests merged in 2024-12, with the labels that each got.

#1679 Ensure `pepper.php` plugin file is not included in builds
  Gruntfile.js
Labels: type: bug

#1676 Upgrade PHPMailer to version 6.9.3.
  src/wp-includes/PHPMailer/PHPMailer.php
  src/wp-includes/PHPMailer/SMTP.php
Labels: type: wp backport

#1671 Add `d.m.Y` to date format presets on General Settings screen
  src/wp-admin/options-general.php
Labels: type: wp backport

#1690 Align headings in Link Manager correctly
  src/wp-admin/css/edit.css
Labels: type: bug

#1639 Grouped backport of PHPStan fixes
  src/wp-admin/includes/class-wp-privacy-requests-table.php
  src/wp-admin/includes/class-wp-site-health-auto-updates.php
  src/wp-includes/class-wp-comment.php
  src/wp-includes/class-wp-query.php
  src/wp-includes/class-wp-recovery-mode.php
  src/wp-includes/class-wp-widget.php
  src/wp-includes/formatting.php
  src/wp-includes/ms-functions.php
  src/wp-includes/option.php
  src/wp-includes/rest-api/endpoints/class-wp-rest-users-controller.php
  src/xmlrpc.php
Labels: type: wp backport

#1646 Restore Comment_Walker::comment function
  src/wp-includes/class-walker-comment.php
  tests/phpunit/tests/comment/cpWalker.php
Labels: type: bug

#1686 Add "Copy" button to "All Settings" screen
  src/wp-admin/options.php
Labels: type: feature request
