Repository ClassicPress/ClassicPress, pull requests merged in 2025-03, with the labels that each got.

#1838 Fix broken `sprintf()` call when deleting a backup
  src/wp-admin/includes/class-wp-upgrader.php
Labels: type: wp backport

#1815 Fix "postboxes is not defined"
  src/wp-admin/js/comment.js
Labels: type: bug

#1829 Fix fatal when listing incompatible plugins
  src/wp-admin/includes/class-wp-plugins-list-table.php
Labels: type: bug

#1835 Fix WP-CLI
  src/wp-includes/class-fix-wpcli.php
Labels: type: bug

#1824 Fix unneeded extra 10px for images
  src/wp-includes/media.php
  tests/phpunit/tests/media.php
  tests/phpunit/tests/shortcode.php
  tests/phpunit/tests/widgets/wpWidgetMediaImage.php
Labels: type: bug

#1832 Fix gallery editor sortable functionality
  src/wp-admin/widgets-form.php
  src/wp-includes/media.php
Labels: type: bug

#1830 Fix id extraction for deleteItem
  src/wp-includes/js/media-grid.js
Labels: type: bug

#1823 Port some CSS from PR #1771
  src/wp-admin/css/media.css
  src/wp-includes/js/media-grid.js
Labels: type: feature request

#1834 Update upload.php to add ID for aria-describedby attribute
  src/wp-admin/upload.php
Labels: type: bug

#1819 Media image widget
  src/wp-admin/css/widgets.css
  src/wp-admin/customize.php
  src/wp-admin/js/customize-widgets.js
  src/wp-admin/js/image-edit.js
  src/wp-admin/js/widgets/media-image-widget.js
  src/wp-admin/widgets-form.php
  src/wp-includes/css/media-views.css
  src/wp-includes/widgets/class-wp-widget-media-image.php
  src/wp-includes/widgets/class-wp-widget-media.php
  tests/phpunit/tests/widgets/wpWidgetMediaImage.php
  tests/qunit/index.html
  tests/qunit/wp-admin/js/widgets/test-media-image-widget.js
Labels: flag: build change
