Repository ClassicPress/ClassicPress, pull requests merged in 2025-01, with the labels that each got.

#1700 Update copyright year in license.txt
  src/license.txt
Labels: flag: high priority

#1658 Remove usage of mysql2date in generate_postdata method
  src/wp-includes/class-wp-query.php
Labels: type: wp backport

#1659 Use WP_Query internally in get_pages
  src/wp-includes/post.php
  tests/phpunit/tests/post/getPages.php
Labels: type: wp backport

#1660 Improve `_load_textdomain_just_in_time()` logic when there are no translation files
  src/wp-includes/class-wp-textdomain-registry.php
  src/wp-includes/l10n.php
  tests/phpunit/tests/l10n/loadTextdomainJustInTime.php
  tests/phpunit/tests/l10n/wpLocaleSwitcher.php
Labels: type: wp backport

#1661 Create a temporary backup of plugins and themes before updating
  src/wp-admin/includes/class-plugin-upgrader.php
  src/wp-admin/includes/class-theme-upgrader.php
  src/wp-admin/includes/class-wp-site-health.php
  src/wp-admin/includes/class-wp-upgrader.php
  src/wp-includes/update.php
Labels: type: wp backport

#1662 Automatically add `fetchpriority="high"` to hero image to improve load time performance
  src/wp-includes/default-filters.php
  src/wp-includes/deprecated.php
  src/wp-includes/media.php
  src/wp-includes/pluggable.php
  src/wp-includes/post-thumbnail-template.php
  src/wp-includes/shortcodes.php
  src/wp-includes/theme.php
  src/wp-includes/widgets/class-wp-widget-media-image.php
  tests/phpunit/tests/media.php
  tests/phpunit/tests/post/thumbnails.php
  tests/phpunit/tests/theme/customHeader.php
  tests/phpunit/tests/widgets/wpWidgetMediaImage.php
Labels: type: wp backport

#1656 Add Support for AVIF image format
  phpcs.xml.dist
  src/wp-admin/includes/image-edit.php
  src/wp-admin/includes/image.php
  src/wp-admin/includes/media.php
  src/wp-admin/includes/schema.php
  src/wp-admin/upload.php
  src/wp-includes/class-avif-info.php
  src/wp-includes/class-wp-image-editor-gd.php
  src/wp-includes/class-wp-image-editor-imagick.php
  src/wp-includes/class-wp-image-editor.php
  src/wp-includes/class-wp-theme.php
  src/wp-includes/compat.php
  src/wp-includes/customize/class-wp-customize-media-control.php
  src/wp-includes/deprecated.php
  src/wp-includes/formatting.php
  src/wp-includes/functions.php
  src/wp-includes/js/media-grid.js
  src/wp-includes/js/media-views.js
  src/wp-includes/js/media/controllers/library.js
  src/wp-includes/js/media/views/image-details.js
  src/wp-includes/js/plupload/handlers.js
  src/wp-includes/js/plupload/wp-plupload.js
  src/wp-includes/js/thickbox/thickbox.js
  src/wp-includes/media.php
  src/wp-includes/post.php
  src/wp-includes/rest-api/endpoints/class-wp-rest-attachments-controller.php
  tests/phpunit/data/images/avif-animated.avif
  tests/phpunit/data/images/avif-lossless.avif
  tests/phpunit/data/images/avif-lossy.avif
  tests/phpunit/data/images/avif-transparent.avif
  tests/phpunit/data/images/color_grid_alpha_nogrid.avif
  tests/phpunit/data/images/colors_hdr_p3.avif
  tests/phpunit/tests/functions.php
  tests/phpunit/tests/image/editor.php
  tests/phpunit/tests/image/functions.php
  tests/phpunit/tests/image/resize.php
  tests/phpunit/tests/rest-api/rest-attachments-controller.php
Labels: type: feature request

#1685 Change wording for expected compatibility when updating
  src/wp-admin/update-core.php
Labels: type: feature request

#1698 Eliminate erroneous restore backup notice
  src/wp-admin/post.php
Labels: type: bug

#1708 Ensure images are displayed in Media List View
  src/wp-admin/css/list-tables.css
Labels: type: bug

#1712 Correct bulk author update of attachments
  src/wp-admin/includes/media.php
Labels: type: bug

#1713 Make images in gallery widget sortable via drag and drop
  src/wp-admin/widgets-form.php
Labels: type: bug

#1699 Ensure LOGGED_IN_COOKIE is not validated when installing
  src/wp-includes/user.php
Labels: type: bug

#1707 Remove unnecessary CSS media query
  src/wp-admin/css/common.css
Labels: type: bug

#1735 Fix wrong author in media grid view
  src/wp-admin/upload.php
  src/wp-includes/js/media-grid.js
Labels: type: bug

#1736 Correct misalignment of input boxes on media list quick edit
  src/wp-admin/css/list-tables.css
Labels: type: bug

#1738 Improve Media Quick Edit Functionality
  src/wp-admin/includes/ajax-actions.php
  src/wp-admin/includes/class-wp-media-list-table.php
  src/wp-admin/js/media.js
Labels: type: bug

#1755 Eliminate errors in browser console when deactivating all dashboard widgets
  src/wp-admin/js/postbox.js
Labels: type: bug

#1753 Prevent multiple race conditions in Media Library
  src/wp-includes/js/media-grid.js
Labels: type: bug

#1754 Replace jQuery with vanilla JavaScript in wp-medialement.js
  src/wp-includes/js/mediaelement/wp-mediaelement.js
Labels: type: bug

#1756 Media dialog contextual pagination with button navigation repositioning
  src/wp-admin/css/media-grid.css
  src/wp-admin/css/media.css
  src/wp-admin/upload.php
  src/wp-includes/js/media-grid.js
Labels: type: feature request

#1742 Ensure Imagick quality is set correctly
  src/wp-includes/class-wp-image-editor-imagick.php
  tests/phpunit/tests/media.php
Labels: type: wp backport
