Repository ClassicPress/ClassicPress, pull requests merged in 2025-09, with the labels that each got.

#2082 Add coverage check to external-http PHPUnit job
  .github/workflows/phpunit-tests.yml
Labels: scope: build/tests

#2020 List distributed dependencies correctly
  package-lock.json
  package.json
Labels: scope: build/tests

#2013 Add `mediaelement` as dependency and introduce build steps
  Gruntfile.js
  package-lock.json
  package.json
  src/wp-includes/js/mediaelement/mediaelement-and-player.js
  src/wp-includes/js/mediaelement/mediaelement-and-player.min.js
  src/wp-includes/js/mediaelement/mediaelement.js
  src/wp-includes/js/mediaelement/mediaelement.min.js
  src/wp-includes/js/mediaelement/mediaelementplayer-legacy.css
  src/wp-includes/js/mediaelement/mediaelementplayer-legacy.min.css
  src/wp-includes/js/mediaelement/mediaelementplayer.min.css
  src/wp-includes/js/mediaelement/wp-mediaelement.css
  src/wp-includes/js/mediaelement/wp-mediaelement.min.css
  src/wp-includes/media.php
Labels: flag: build change

#1998 Ensure password is reverted to `password` input type upon submission.
  src/wp-admin/js/user-profile.js
Labels: type: feature request, type: wp backport

#2042 Set correct canonical admin URL
  src/wp-admin/includes/misc.php
Labels: type: feature request
