Repository ClassicPress/ClassicPress, pull requests merged in 2025-05, with the labels that each got.

#1921 Update "Learn More" URL
  src/wp-admin/options-general.php
Labels: type: bug

#1874 Media image widget without backbone.js at all
  src/wp-admin/css/widgets.css
  src/wp-admin/customize.php
  src/wp-admin/js/widgets/media-image-widget.js
  src/wp-admin/js/widgets/media-widgets.js
  src/wp-admin/widgets-form.php
  src/wp-includes/css/media-views.css
  src/wp-includes/js/filepond/cp-filepond.css
  src/wp-includes/script-loader.php
  src/wp-includes/widgets.php
  src/wp-includes/widgets/class-wp-widget-media-image.php
  tests/qunit/index.html
  tests/qunit/wp-admin/js/widgets/test-media-widgets.js
Labels: type: feature request, flag: build change

#1913 Remove tags from Customizer theme modal for new WP themes
  src/wp-admin/includes/theme.php
Labels: type: bug

#1899 Gallery widget without backbone
  src/wp-admin/css/widgets.css
  src/wp-admin/customize.php
  src/wp-admin/js/widgets/media-gallery-widget.js
  src/wp-admin/js/widgets/media-image-widget.js
  src/wp-admin/widgets-form.php
  src/wp-includes/script-loader.php
  src/wp-includes/widgets/class-wp-widget-media-gallery.php
  src/wp-includes/widgets/class-wp-widget-media-image.php
Labels: type: feature request

#1912 Inject meta into wp prepare attachment for js()
  src/wp-admin/includes/media.php
  src/wp-admin/upload.php
Labels: type: feature request

#1914 Audio widget without backbone
  src/wp-admin/css/widgets.css
  src/wp-admin/customize.php
  src/wp-admin/js/widgets/media-audio-widget.js
  src/wp-admin/widgets-form.php
  src/wp-includes/script-loader.php
  src/wp-includes/widgets/class-wp-widget-media-audio.php
  src/wp-includes/widgets/class-wp-widget-media.php
Labels: type: feature request

#1915 Video widget without backbone
  src/wp-admin/customize.php
  src/wp-admin/js/widgets/media-video-widget.js
  src/wp-admin/widgets-form.php
  src/wp-includes/script-loader.php
  src/wp-includes/widgets/class-wp-widget-media-video.php
Labels: type: feature request

#1936 Update workflow runs to use concurrency
  .github/workflows/phpunit-tests.yml
Labels: scope: build/tests

#1945 Update and fix color picker slider in Customizer
  src/wp-admin/css/color-picker.css
  src/wp-admin/css/revisions.css
  src/wp-admin/js/iris.js
Labels: type: bug

#1951 Avoid errors when media in widgets is missing
  src/wp-includes/widgets/class-wp-widget-media-audio.php
  src/wp-includes/widgets/class-wp-widget-media-gallery.php
  src/wp-includes/widgets/class-wp-widget-media-image.php
  src/wp-includes/widgets/class-wp-widget-media-video.php
Labels: type: bug

#1929 Theme screens without backbone
  src/wp-admin/css/themes.css
  src/wp-admin/includes/ajax-actions.php
  src/wp-admin/js/theme.js
  src/wp-admin/theme-install.php
  src/wp-admin/themes.php
  src/wp-includes/script-loader.php
Labels: type: feature request
