Repository ClassicPress/ClassicPress, pull requests merged in 2025-04, with the labels that each got.

#1820 Media gallery widget
  src/wp-admin/css/widgets.css
  src/wp-admin/js/widgets/media-gallery-widget.js
  src/wp-includes/widgets/class-wp-widget-media-gallery.php
  tests/phpunit/tests/widgets/wpWidgetMediaGallery.php
  tests/qunit/index.html
  tests/qunit/wp-admin/js/widgets/test-media-gallery-widget.js
Labels: flag: build change

#1821 Media audio widget
  src/wp-admin/js/widgets/media-audio-widget.js
  src/wp-includes/widgets/class-wp-widget-media-audio.php
  tests/phpunit/tests/widgets/wpWidgetMediaAudio.php
  tests/qunit/index.html
Labels: flag: build change

#1845 Improve formatting of user taxonomy terms on user-edit page
  src/wp-admin/includes/user.php
  src/wp-admin/user-edit.php
Labels: type: feature request

#1880 Correct typo for file upload gallery
  src/wp-admin/js/gallery.js
Labels: type: bug

#1878 Ensure video can be added to media video widget
  src/wp-admin/js/widgets/media-video-widget.js
  src/wp-includes/js/mediaelement/mediaelementplayer-legacy.css
  src/wp-includes/media.php
  src/wp-includes/widgets/class-wp-widget-media-video.php
Labels: type: bug

#1893 Fix problem with `post__in` parameter in wp_ajax_query_attachments()
  src/wp-admin/includes/ajax-actions.php
Labels: type: bug

#1837 Fix Quick Edit in Media Library
  src/wp-admin/includes/ajax-actions.php
  src/wp-admin/includes/class-wp-media-list-table.php
  src/wp-admin/js/media.js
Labels: type: bug

#1897 Add data ID to li elements in media grid
  src/wp-admin/upload.php
  src/wp-includes/js/media-grid.js
Labels: type: code improvement

#1884 Extend JavaScript linting to more core files
  Gruntfile.js
  src/wp-includes/js/media-grid.js
Labels: flag: build change

#1901 Replace an empty `foreach` loop in `wp_replace_in_html_tags()`
  src/wp-includes/formatting.php
Labels: type: wp backport

#1902 Protect comments in editor content when switching tabs
  src/wp-admin/css/edit.css
  src/wp-admin/edit-form-advanced.php
  src/wp-admin/js/editor.js
  src/wp-admin/js/post.js
  src/wp-includes/class-wp-editor.php
  src/wp-includes/css/editor.css
Labels: type: bug, type: wp backport

#1891 Improve keyboard navigation in Themes screen
  src/wp-admin/js/theme.js
Labels: type: code improvement

#1894 ClassicPress theme - tweaks and such in stylesheet
  src/wp-content/themes/the-classicpress-theme/style.css
Labels: type: code improvement

#1895 ClassicPress theme - updated editor styles to match the frontend
  src/wp-content/themes/the-classicpress-theme/css/editor-style.css
  src/wp-content/themes/the-classicpress-theme/editor-style.css
  src/wp-content/themes/the-classicpress-theme/functions.php
Labels: type: code improvement
