Repository ClassicPress/ClassicPress, pull requests merged in 2025-08, with the labels that each got.

#2057 Update media-grid.js to remove superfluous alt attribute in modal
  src/wp-includes/js/media-grid.js
Labels: type: bug

#2070 Separate multisite testing to PHPUnit workflow
  .github/workflows/phpunit-tests.yml
Labels: scope: build/tests

#2086 Improve display of warnings for incompatible theme updates
  src/wp-admin/js/theme.js
  src/wp-admin/themes.php
Labels: type: bug

#2052 The ClassicPress Theme - minor CSS tweaks
  src/wp-content/themes/the-classicpress-theme/style.css
Labels: type: feature request
